(* Generated by re2ocaml 4.5.1 *)
#1 "lexer.re2c"
open String  (* for unqualified unsafe_get used in generated code *)

type lexbuf = {
  yyinput : string;
  yylimit : int;
  mutable yycursor : int;
  mutable yymarker : int;
  mutable yyt1 : int;
  (* Tags capturing the start/end of an IDENT or TYVAR lexeme. *)
  mutable t1 : int;
  mutable t2 : int;
}

let make input =
  { yyinput = input;
    yylimit = String.length input;
    yycursor = 0;
    yymarker = 0;
    yyt1 = 0;
    t1 = -1;
    t2 = -1;
  }


#28 "lexer.ml"
let rec yy0 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\t'..'\n'
        | '\r'
        | ' ' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy3 [@tailcall]) yyrecord
        | '\'' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy5 [@tailcall]) yyrecord
        | '(' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy6 [@tailcall]) yyrecord
        | ')' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy7 [@tailcall]) yyrecord
        | ',' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy8 [@tailcall]) yyrecord
        | '-' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy9 [@tailcall]) yyrecord
        | '.' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy10 [@tailcall]) yyrecord
        | ':' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy12 [@tailcall]) yyrecord
        | '=' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy14 [@tailcall]) yyrecord
        | 'A'..'Z'
        | '_'
        | 'c'..'d'
        | 'g'..'h'
        | 'j'..'k'
        | 'm'..'q'
        | 's'
        | 'u'..'v'
        | 'x'..'z' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | 'a' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy19 [@tailcall]) yyrecord
        | 'b' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy20 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy21 [@tailcall]) yyrecord
        | 'f' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy22 [@tailcall]) yyrecord
        | 'i' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy23 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy24 [@tailcall]) yyrecord
        | 'r' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy25 [@tailcall]) yyrecord
        | 't' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy26 [@tailcall]) yyrecord
        | 'w' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy27 [@tailcall]) yyrecord
        | '{' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy28 [@tailcall]) yyrecord
        | '}' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy29 [@tailcall]) yyrecord
        | _ ->
            if (yyrecord.yylimit <= yyrecord.yycursor) then (
                (yy89 [@tailcall]) yyrecord
            ) else (
                yyrecord.yycursor <- yyrecord.yycursor + 1;
                (yy1 [@tailcall]) yyrecord
            )

and yy1 (yyrecord : lexbuf) : Parser.token =
    (yy2 [@tailcall]) yyrecord

and yy2 (yyrecord : lexbuf) : Parser.token =
#31 "lexer.re2c"
    failwith (Printf.sprintf "lexer: unexpected char at offset %d" yyrecord.yycursor)
#130 "lexer.ml"

and yy3 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\t'..'\n'
        | '\r'
        | ' ' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy3 [@tailcall]) yyrecord
        | _ -> (yy4 [@tailcall]) yyrecord

and yy4 (yyrecord : lexbuf) : Parser.token =
#33 "lexer.re2c"
    lex yyrecord
#145 "lexer.ml"

and yy5 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | 'A'..'Z'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy30 [@tailcall]) yyrecord
        | _ -> (yy2 [@tailcall]) yyrecord

and yy6 (yyrecord : lexbuf) : Parser.token =
#60 "lexer.re2c"
    Parser.LPAREN
#159 "lexer.ml"

and yy7 (yyrecord : lexbuf) : Parser.token =
#61 "lexer.re2c"
    Parser.RPAREN
#164 "lexer.ml"

and yy8 (yyrecord : lexbuf) : Parser.token =
#59 "lexer.re2c"
    Parser.COMMA
#169 "lexer.ml"

and yy9 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '>' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy32 [@tailcall]) yyrecord
        | _ -> (yy2 [@tailcall]) yyrecord

and yy10 (yyrecord : lexbuf) : Parser.token =
    yyrecord.yymarker <- yyrecord.yycursor;
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '.' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy33 [@tailcall]) yyrecord
        | _ -> (yy11 [@tailcall]) yyrecord

and yy11 (yyrecord : lexbuf) : Parser.token =
#58 "lexer.re2c"
    Parser.DOT
#191 "lexer.ml"

and yy12 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | ':' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy35 [@tailcall]) yyrecord
        | _ -> (yy13 [@tailcall]) yyrecord

and yy13 (yyrecord : lexbuf) : Parser.token =
#57 "lexer.re2c"
    Parser.COLON
#204 "lexer.ml"

and yy14 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '>' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy36 [@tailcall]) yyrecord
        | _ -> (yy15 [@tailcall]) yyrecord

and yy15 (yyrecord : lexbuf) : Parser.token =
#55 "lexer.re2c"
    Parser.EQ
#217 "lexer.ml"

and yy16 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    (yy17 [@tailcall]) yyrecord yych

and yy17 (yyrecord : lexbuf) (yych : char) : Parser.token =
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy18 [@tailcall]) yyrecord

and yy18 (yyrecord : lexbuf) : Parser.token =
    yyrecord.t1 <- yyrecord.yyt1;
    yyrecord.t2 <- yyrecord.yycursor;
#69 "lexer.re2c"
    
    Parser.IDENT (String.sub yyrecord.yyinput yyrecord.t1 (yyrecord.t2 - yyrecord.t1))

#240 "lexer.ml"

and yy19 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'n' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy37 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy20 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'o' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy38 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy21 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy39 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy22 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'a' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy40 [@tailcall]) yyrecord
        | 'o' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy41 [@tailcall]) yyrecord
        | 'u' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy42 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy23 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'f' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy43 [@tailcall]) yyrecord
        | 'n' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy45 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy24 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy47 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy25 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy48 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy26 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'h' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy49 [@tailcall]) yyrecord
        | 'r' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy50 [@tailcall]) yyrecord
        | 'y' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy51 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy27 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'i' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy52 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy28 (yyrecord : lexbuf) : Parser.token =
#62 "lexer.re2c"
    Parser.LBRACE
#341 "lexer.ml"

and yy29 (yyrecord : lexbuf) : Parser.token =
#63 "lexer.re2c"
    Parser.RBRACE
#346 "lexer.ml"

and yy30 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\''
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy30 [@tailcall]) yyrecord
        | _ -> (yy31 [@tailcall]) yyrecord

and yy31 (yyrecord : lexbuf) : Parser.token =
    yyrecord.t1 <- yyrecord.yyt1;
    yyrecord.t2 <- yyrecord.yycursor;
#72 "lexer.re2c"
    
    Parser.TYVAR (String.sub yyrecord.yyinput yyrecord.t1 (yyrecord.t2 - yyrecord.t1))

#367 "lexer.ml"

and yy32 (yyrecord : lexbuf) : Parser.token =
#53 "lexer.re2c"
    Parser.ARROW
#372 "lexer.ml"

and yy33 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '.' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy53 [@tailcall]) yyrecord
        | _ -> (yy34 [@tailcall]) yyrecord

and yy34 (yyrecord : lexbuf) : Parser.token =
    yyrecord.yycursor <- yyrecord.yymarker;
    (yy11 [@tailcall]) yyrecord

and yy35 (yyrecord : lexbuf) : Parser.token =
#56 "lexer.re2c"
    Parser.COLONCOLON
#389 "lexer.ml"

and yy36 (yyrecord : lexbuf) : Parser.token =
#54 "lexer.re2c"
    Parser.FATARROW
#394 "lexer.ml"

and yy37 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'd' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy54 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy38 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'o' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy56 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy39 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 's' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy57 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy40 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy58 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy41 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'r' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy59 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy42 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'n' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy60 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy43 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy44 [@tailcall]) yyrecord

and yy44 (yyrecord : lexbuf) : Parser.token =
#41 "lexer.re2c"
    Parser.IF
#464 "lexer.ml"

and yy45 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy46 [@tailcall]) yyrecord

and yy46 (yyrecord : lexbuf) : Parser.token =
#39 "lexer.re2c"
    Parser.IN
#480 "lexer.ml"

and yy47 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 't' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy62 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy48 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'c' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy64 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy49 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy66 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy50 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'u' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy67 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy51 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'p' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy68 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy52 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 't' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy69 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy53 (yyrecord : lexbuf) : Parser.token =
#52 "lexer.re2c"
    Parser.DOTS
#539 "lexer.ml"

and yy54 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy55 [@tailcall]) yyrecord

and yy55 (yyrecord : lexbuf) : Parser.token =
#38 "lexer.re2c"
    Parser.AND
#555 "lexer.ml"

and yy56 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy70 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy57 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy72 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy58 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 's' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy74 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy59 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'a' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy75 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy60 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy61 [@tailcall]) yyrecord

and yy61 (yyrecord : lexbuf) : Parser.token =
#40 "lexer.re2c"
    Parser.FUN
#607 "lexer.ml"

and yy62 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy63 [@tailcall]) yyrecord

and yy63 (yyrecord : lexbuf) : Parser.token =
#36 "lexer.re2c"
    Parser.LET
#623 "lexer.ml"

and yy64 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy65 [@tailcall]) yyrecord

and yy65 (yyrecord : lexbuf) : Parser.token =
#37 "lexer.re2c"
    Parser.REC
#639 "lexer.ml"

and yy66 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'n' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy76 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy67 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy78 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy68 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy80 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy69 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'h' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy82 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy70 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy71 [@tailcall]) yyrecord

and yy71 (yyrecord : lexbuf) : Parser.token =
#48 "lexer.re2c"
    Parser.BOOL
#691 "lexer.ml"

and yy72 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy73 [@tailcall]) yyrecord

and yy73 (yyrecord : lexbuf) : Parser.token =
#43 "lexer.re2c"
    Parser.ELSE
#707 "lexer.ml"

and yy74 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy84 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy75 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy86 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy76 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy77 [@tailcall]) yyrecord

and yy77 (yyrecord : lexbuf) : Parser.token =
#42 "lexer.re2c"
    Parser.THEN
#741 "lexer.ml"

and yy78 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy79 [@tailcall]) yyrecord

and yy79 (yyrecord : lexbuf) : Parser.token =
#44 "lexer.re2c"
    Parser.TRUE
#757 "lexer.ml"

and yy80 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy81 [@tailcall]) yyrecord

and yy81 (yyrecord : lexbuf) : Parser.token =
#47 "lexer.re2c"
    Parser.TYPE
#773 "lexer.ml"

and yy82 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy83 [@tailcall]) yyrecord

and yy83 (yyrecord : lexbuf) : Parser.token =
#46 "lexer.re2c"
    Parser.WITH
#789 "lexer.ml"

and yy84 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy85 [@tailcall]) yyrecord

and yy85 (yyrecord : lexbuf) : Parser.token =
#45 "lexer.re2c"
    Parser.FALSE
#805 "lexer.ml"

and yy86 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy87 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy87 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy88 [@tailcall]) yyrecord

and yy88 (yyrecord : lexbuf) : Parser.token =
#49 "lexer.re2c"
    Parser.FORALL
#830 "lexer.ml"

and yy89 (yyrecord : lexbuf) : Parser.token =
#32 "lexer.re2c"
    Parser.EOF
#835 "lexer.ml"

and lex (yyrecord : lexbuf) : Parser.token =
    (yy0 [@tailcall]) yyrecord

#75 "lexer.re2c"

