(* Generated by re2ocaml 4.5.1 *)
#1 "lexer.re2c"
open String  (* for unqualified unsafe_get used in generated code *)

type lexbuf = {
  yyinput : string;
  yylimit : int;
  mutable yycursor : int;
  mutable yymarker : int;
  mutable yyt1 : int;
  (* Tags capturing the start/end of an IDENT or TYVAR lexeme. *)
  mutable t1 : int;
  mutable t2 : int;
}

let make input =
  { yyinput = input;
    yylimit = String.length input;
    yycursor = 0;
    yymarker = 0;
    yyt1 = 0;
    t1 = -1;
    t2 = -1;
  }


#28 "lexer.ml"
let rec yy0 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\t'..'\n'
        | '\r'
        | ' ' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy3 [@tailcall]) yyrecord
        | '\'' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy5 [@tailcall]) yyrecord
        | '(' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy6 [@tailcall]) yyrecord
        | ')' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy7 [@tailcall]) yyrecord
        | ',' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy8 [@tailcall]) yyrecord
        | '-' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy9 [@tailcall]) yyrecord
        | '.' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy10 [@tailcall]) yyrecord
        | ':' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy12 [@tailcall]) yyrecord
        | '=' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy14 [@tailcall]) yyrecord
        | 'A'..'Z'
        | '_'
        | 'c'..'d'
        | 'g'..'h'
        | 'j'..'k'
        | 'm'..'q'
        | 's'
        | 'u'..'v'
        | 'x'..'z' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | 'a' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy19 [@tailcall]) yyrecord
        | 'b' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy20 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy21 [@tailcall]) yyrecord
        | 'f' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy22 [@tailcall]) yyrecord
        | 'i' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy23 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy24 [@tailcall]) yyrecord
        | 'r' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy25 [@tailcall]) yyrecord
        | 't' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy26 [@tailcall]) yyrecord
        | 'w' ->
            yyrecord.yyt1 <- yyrecord.yycursor;
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy27 [@tailcall]) yyrecord
        | '{' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy28 [@tailcall]) yyrecord
        | '|' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy29 [@tailcall]) yyrecord
        | '}' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy30 [@tailcall]) yyrecord
        | _ ->
            if (yyrecord.yylimit <= yyrecord.yycursor) then (
                (yy101 [@tailcall]) yyrecord
            ) else (
                yyrecord.yycursor <- yyrecord.yycursor + 1;
                (yy1 [@tailcall]) yyrecord
            )

and yy1 (yyrecord : lexbuf) : Parser.token =
    (yy2 [@tailcall]) yyrecord

and yy2 (yyrecord : lexbuf) : Parser.token =
#31 "lexer.re2c"
    failwith (Printf.sprintf "lexer: unexpected char at offset %d" yyrecord.yycursor)
#133 "lexer.ml"

and yy3 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\t'..'\n'
        | '\r'
        | ' ' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy3 [@tailcall]) yyrecord
        | _ -> (yy4 [@tailcall]) yyrecord

and yy4 (yyrecord : lexbuf) : Parser.token =
#33 "lexer.re2c"
    lex yyrecord
#148 "lexer.ml"

and yy5 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | 'A'..'Z'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy31 [@tailcall]) yyrecord
        | _ -> (yy2 [@tailcall]) yyrecord

and yy6 (yyrecord : lexbuf) : Parser.token =
#62 "lexer.re2c"
    Parser.LPAREN
#162 "lexer.ml"

and yy7 (yyrecord : lexbuf) : Parser.token =
#63 "lexer.re2c"
    Parser.RPAREN
#167 "lexer.ml"

and yy8 (yyrecord : lexbuf) : Parser.token =
#61 "lexer.re2c"
    Parser.COMMA
#172 "lexer.ml"

and yy9 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '>' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy33 [@tailcall]) yyrecord
        | _ -> (yy2 [@tailcall]) yyrecord

and yy10 (yyrecord : lexbuf) : Parser.token =
    yyrecord.yymarker <- yyrecord.yycursor;
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '.' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy34 [@tailcall]) yyrecord
        | _ -> (yy11 [@tailcall]) yyrecord

and yy11 (yyrecord : lexbuf) : Parser.token =
#60 "lexer.re2c"
    Parser.DOT
#194 "lexer.ml"

and yy12 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | ':' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy36 [@tailcall]) yyrecord
        | _ -> (yy13 [@tailcall]) yyrecord

and yy13 (yyrecord : lexbuf) : Parser.token =
#59 "lexer.re2c"
    Parser.COLON
#207 "lexer.ml"

and yy14 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '>' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy37 [@tailcall]) yyrecord
        | _ -> (yy15 [@tailcall]) yyrecord

and yy15 (yyrecord : lexbuf) : Parser.token =
#57 "lexer.re2c"
    Parser.EQ
#220 "lexer.ml"

and yy16 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    (yy17 [@tailcall]) yyrecord yych

and yy17 (yyrecord : lexbuf) (yych : char) : Parser.token =
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy18 [@tailcall]) yyrecord

and yy18 (yyrecord : lexbuf) : Parser.token =
    yyrecord.t1 <- yyrecord.yyt1;
    yyrecord.t2 <- yyrecord.yycursor;
#72 "lexer.re2c"
    
    Parser.IDENT (String.sub yyrecord.yyinput yyrecord.t1 (yyrecord.t2 - yyrecord.t1))

#243 "lexer.ml"

and yy19 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'n' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy38 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy20 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'o' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy39 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy21 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy40 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy22 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'a' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy41 [@tailcall]) yyrecord
        | 'o' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy42 [@tailcall]) yyrecord
        | 'u' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy43 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy23 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'f' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy44 [@tailcall]) yyrecord
        | 'n' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy46 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy24 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy48 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy25 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy49 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy26 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'h' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy50 [@tailcall]) yyrecord
        | 'r' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy51 [@tailcall]) yyrecord
        | 'y' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy52 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy27 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'i' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy53 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy28 (yyrecord : lexbuf) : Parser.token =
#64 "lexer.re2c"
    Parser.LBRACE
#344 "lexer.ml"

and yy29 (yyrecord : lexbuf) : Parser.token =
#66 "lexer.re2c"
    Parser.PIPE
#349 "lexer.ml"

and yy30 (yyrecord : lexbuf) : Parser.token =
#65 "lexer.re2c"
    Parser.RBRACE
#354 "lexer.ml"

and yy31 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\''
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy31 [@tailcall]) yyrecord
        | _ -> (yy32 [@tailcall]) yyrecord

and yy32 (yyrecord : lexbuf) : Parser.token =
    yyrecord.t1 <- yyrecord.yyt1;
    yyrecord.t2 <- yyrecord.yycursor;
#75 "lexer.re2c"
    
    Parser.TYVAR (String.sub yyrecord.yyinput yyrecord.t1 (yyrecord.t2 - yyrecord.t1))

#375 "lexer.ml"

and yy33 (yyrecord : lexbuf) : Parser.token =
#55 "lexer.re2c"
    Parser.ARROW
#380 "lexer.ml"

and yy34 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '.' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy54 [@tailcall]) yyrecord
        | _ -> (yy35 [@tailcall]) yyrecord

and yy35 (yyrecord : lexbuf) : Parser.token =
    yyrecord.yycursor <- yyrecord.yymarker;
    (yy11 [@tailcall]) yyrecord

and yy36 (yyrecord : lexbuf) : Parser.token =
#58 "lexer.re2c"
    Parser.COLONCOLON
#397 "lexer.ml"

and yy37 (yyrecord : lexbuf) : Parser.token =
#56 "lexer.re2c"
    Parser.FATARROW
#402 "lexer.ml"

and yy38 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'd' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy55 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy39 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'o' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy57 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy40 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 's' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy58 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy41 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy59 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy42 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'r' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy60 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy43 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'n' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy61 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy44 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy45 [@tailcall]) yyrecord

and yy45 (yyrecord : lexbuf) : Parser.token =
#41 "lexer.re2c"
    Parser.IF
#472 "lexer.ml"

and yy46 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'r'
        | 't'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | 's' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy63 [@tailcall]) yyrecord
        | _ -> (yy47 [@tailcall]) yyrecord

and yy47 (yyrecord : lexbuf) : Parser.token =
#39 "lexer.re2c"
    Parser.IN
#492 "lexer.ml"

and yy48 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 't' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy64 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy49 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'c' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy66 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy50 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy68 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy51 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'a' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy69 [@tailcall]) yyrecord
        | 'u' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy70 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy52 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'p' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy71 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy53 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 't' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy72 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy54 (yyrecord : lexbuf) : Parser.token =
#54 "lexer.re2c"
    Parser.DOTS
#554 "lexer.ml"

and yy55 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy56 [@tailcall]) yyrecord

and yy56 (yyrecord : lexbuf) : Parser.token =
#38 "lexer.re2c"
    Parser.AND
#570 "lexer.ml"

and yy57 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy73 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy58 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy75 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy59 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 's' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy77 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy60 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'a' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy78 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy61 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy62 [@tailcall]) yyrecord

and yy62 (yyrecord : lexbuf) : Parser.token =
#40 "lexer.re2c"
    Parser.FUN
#622 "lexer.ml"

and yy63 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 't' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy79 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy64 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy65 [@tailcall]) yyrecord

and yy65 (yyrecord : lexbuf) : Parser.token =
#36 "lexer.re2c"
    Parser.LET
#647 "lexer.ml"

and yy66 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy67 [@tailcall]) yyrecord

and yy67 (yyrecord : lexbuf) : Parser.token =
#37 "lexer.re2c"
    Parser.REC
#663 "lexer.ml"

and yy68 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'n' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy80 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy69 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'i' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy82 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy70 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy83 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy71 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy85 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy72 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'h' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy87 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy73 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy74 [@tailcall]) yyrecord

and yy74 (yyrecord : lexbuf) : Parser.token =
#48 "lexer.re2c"
    Parser.BOOL
#724 "lexer.ml"

and yy75 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy76 [@tailcall]) yyrecord

and yy76 (yyrecord : lexbuf) : Parser.token =
#43 "lexer.re2c"
    Parser.ELSE
#740 "lexer.ml"

and yy77 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy89 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy78 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy91 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy79 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'a' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy92 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy80 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy81 [@tailcall]) yyrecord

and yy81 (yyrecord : lexbuf) : Parser.token =
#42 "lexer.re2c"
    Parser.THEN
#783 "lexer.ml"

and yy82 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 't' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy93 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy83 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy84 [@tailcall]) yyrecord

and yy84 (yyrecord : lexbuf) : Parser.token =
#44 "lexer.re2c"
    Parser.TRUE
#808 "lexer.ml"

and yy85 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy86 [@tailcall]) yyrecord

and yy86 (yyrecord : lexbuf) : Parser.token =
#47 "lexer.re2c"
    Parser.TYPE
#824 "lexer.ml"

and yy87 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy88 [@tailcall]) yyrecord

and yy88 (yyrecord : lexbuf) : Parser.token =
#46 "lexer.re2c"
    Parser.WITH
#840 "lexer.ml"

and yy89 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy90 [@tailcall]) yyrecord

and yy90 (yyrecord : lexbuf) : Parser.token =
#45 "lexer.re2c"
    Parser.FALSE
#856 "lexer.ml"

and yy91 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'l' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy95 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy92 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'n' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy97 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy93 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy94 [@tailcall]) yyrecord

and yy94 (yyrecord : lexbuf) : Parser.token =
#50 "lexer.re2c"
    Parser.TRAIT
#890 "lexer.ml"

and yy95 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy96 [@tailcall]) yyrecord

and yy96 (yyrecord : lexbuf) : Parser.token =
#49 "lexer.re2c"
    Parser.FORALL
#906 "lexer.ml"

and yy97 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'c' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy98 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy98 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '\x00' -> (yy18 [@tailcall]) yyrecord
        | 'e' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy99 [@tailcall]) yyrecord
        | _ -> (yy17 [@tailcall]) yyrecord yych

and yy99 (yyrecord : lexbuf) : Parser.token =
    let yych = unsafe_get yyrecord.yyinput yyrecord.yycursor in
    match yych with
        | '0'..'9'
        | 'A'..'Z'
        | '_'
        | 'a'..'z' ->
            yyrecord.yycursor <- yyrecord.yycursor + 1;
            (yy16 [@tailcall]) yyrecord
        | _ -> (yy100 [@tailcall]) yyrecord

and yy100 (yyrecord : lexbuf) : Parser.token =
#51 "lexer.re2c"
    Parser.INSTANCE
#940 "lexer.ml"

and yy101 (yyrecord : lexbuf) : Parser.token =
#32 "lexer.re2c"
    Parser.EOF
#945 "lexer.ml"

and lex (yyrecord : lexbuf) : Parser.token =
    (yy0 [@tailcall]) yyrecord

#78 "lexer.re2c"

